default: &default
  adapter: postgresql
  database: saas-project-app
  pool: 5
  username: postgres
  password: 0056asas

development:
  <<: *default
  database: saas-project-app

test:
  <<: *default
  database: saas-project-app

production:
  <<: *default
  database: saas-project-app
